from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.2.1")

##### set configfile #####
configfile: "config/config.yaml"

##### load rules #####

include: "rules/common.smk"
include: "rules/main.smk"

##### target rules #####

rule all:
    input:
        get_final_output()
